version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/core/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/api/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
